const { EmbedBuilder } = require("discord.js");

class Notification {
  constructor(interaction) {
    this.interaction = interaction;
    this.title = null;
    this.description = null;
    this.image = null;
    this.thumbnail = null;
    this.footer = null;
    this.embed = null;
  }

  setTitle(title) {
    this.title = title;
    return this;
  }
  setDescription(description) {
    this.description = description;
    return this;
  }

  setThumbnail(thumbnail) {
    this.thumbnail = thumbnail;
    return this;
  }

  setImage(image) {
    this.image = image;
    return this;
  }

  buildEmbed() {
    this.embed = new EmbedBuilder()
      .setAuthor({
        name: this.interaction.client.user.displayName,
        iconURL: this.interaction.client.user.displayAvatarURL(),
      })
      .setTitle(this.title)
      .setDescription(this.description)
      .setImage(this.image)
      .setThumbnail(this.thumbnail)
      .setFooter({
        text: `Generated by ${this.interaction.client.user.displayName}`,
      })
      .setTimestamp();
    return this;
  }

  async sendNotification() {
    await this.interaction.editReply({ embeds: [this.embed] });
    return this;
  }
}

module.exports = { Notification };
