const { EmbedBuilder } = require("discord.js");

function CreateLeagueEmbedMessage(dataObject) {
  const LeagueEmbedMessage = new EmbedBuilder()
    .setAuthor({
      name: dataObject.client.user.displayName,
      iconURL: dataObject.client.user.displayAvatarURL(),
    })
    .setTitle(dataObject.options.getString("event-name"))
    .setDescription(
      `Event **${dataObject.options.getString("event-name")}** was created by 
        <@${dataObject.user.id}>
      .\nU can join the event by using slash command **/join ${dataObject.options.getString(
        "event-name"
      )}**\nMore info will be posted in event channel by <@${
        dataObject.user.id
      }>.\nWhich you will get access to after you join the event.`
    )
    .setImage(dataObject.options.getAttachment("event-banner").attachment)
    .setFooter({
      text: `Generated by ${dataObject.client.user.displayName}`,
    })
    .setTimestamp();

  return LeagueEmbedMessage;
}

module.exports = {
  CreateLeagueEmbedMessage,
};
